### ISSUE TITLE
Initializing the plugin failed.

### ISSUE THREAD

**Issue by LuoDiKaiHua** [sublimelsp/LSP-lemminx#16]
DPI mode: per-monitor v2
startup, version: 4152 windows x64 channel: stable
executable: /D/Applications/Sublime Text/sublime_text.exe
application: /D/Applications/Sublime Text
working dir: /D/Applications/Sublime Text
packages path: /C/Users/***/AppData/Roaming/Sublime Text/Packages
state path: /C/Users/***/AppData/Roaming/Sublime Text/Local
zip path: /D/Applications/Sublime Text/Packages
zip path: /C/Users/***/AppData/Roaming/Sublime Text/Installed Packages

reloading python 3.3 plugin LSP-lemminx.plugin
Traceback (most recent call last):
  File "D:\Applications\Sublime Text\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Applications\Sublime Text\Lib\python33\sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\***\AppData\Roaming\Sublime Text\Installed Packages\LSP-lemminx.sublime-package\plugin.py", line 11, in <module>
ImportError: No module named 'typing'

**Comment by predragnikolic** [comment]
@deathaxe  if you want to use types, you can import them from `LSP.plugin.core.typing` (you will not get a ImportError that way in py3.3)
```
from LSP.plugin.core.typing import Any, Callable, Mapping, cast, Dict
```
