### ISSUE TITLE
Exception when reading settings

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-lemminx#4]
```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 478, in on_api_ready
    plc()
  File "/home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/main.py", line 26, in startup
    load_handlers()
  File "/home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/registry.py", line 59, in load_handlers
    register_language_handler(handler)
  File "/home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/registry.py", line 65, in register_language_handler
    client_configs.add_external_config(handler.config)
  File "/home/raoul/.config/sublime-text-3/Packages/LSP-lemminx/plugin.py", line 153, in config
    for key, value in merge_configs(default_config, user_config):
  File "/home/raoul/.config/sublime-text-3/Packages/LSP-lemminx/plugin.py", line 29, in merge_configs
    yield key, dict(merge_configs(value, new_value))
  File "/home/raoul/.config/sublime-text-3/Packages/LSP-lemminx/plugin.py", line 29, in merge_configs
    yield key, dict(merge_configs(value, new_value))
  File "/home/raoul/.config/sublime-text-3/Packages/LSP-lemminx/plugin.py", line 32, in merge_configs
    if isinstance(value[0], dict):
IndexError: list index out of range
```

It breaks at reading the `catalogs` value.

**Comment by rchl** [comment]
@deathaxe maybe it would be a good idea to have PRs for changes? I wouldn't mind having a look.

**Comment by deathaxe** [comment]
In combination with setting up some tests, yea.
